version: '3'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 